# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6befcc3b3223687a35a86681d40f02e41e377b91a685445ff2337b6c5930ed2dffa44eb38e733fa7f32940956277ac56538526c79b42300b94eff412fb0982e9

test:
  secret_key_base: 84bd8214d2c5a8ef67f9765ed08bd933782f11d0f002faeea27a90885ddbbc4fbc69682aa1c924db2c66fb47109c9d955e4928c0ba3f261017591559b3090d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
